name: Renovate

on:
  #schedule:
  #  - cron: '0/15 6-18 * * 1,2,3,4,5'
  workflow_dispatch:

permissions: {}

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Retrieve Renovate onboarding configuration
        run: |
          echo "ONBOARDING_CONFIG=$(cat renovate-onboarding-config.json)" >> $GITHUB_ENV

      - name: Run Self-hosted Renovate
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: renovate-runner-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-image: ghcr.io/renovatebot/renovate
          renovate-version: 37.413.3
        env:
          RENOVATE_ONBOARDING_CONFIG: ${{ env.ONBOARDING_CONFIG }}
