name: Renovate

on:
  schedule:
    - cron: '5 5,11 * * 1,2,3,4,5'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run Renovate in dry-run mode'
        required: false
        type: choice
        options:
          - 'extract'
          - 'lookup'
          - 'full'
          - 'off'
        default: 'off'

permissions: {}

concurrency:
  group: renovate

env:
  RENOVATE_CONFIGURATION: renovate-runner-config.json
  RENOVATE_IMAGE: ghcr.io/renovatebot/renovate
  RENOVATE_VERSION: 41.115.2 # renovate: datasource=github-releases depName=renovatebot/renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get application token
        id: get_token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run self-hosted Renovate (Dry Run)
        if: ${{ github.event.inputs.dry_run && github.event.inputs.dry_run != 'off' }}
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: ${{ env.RENOVATE_CONFIGURATION }}
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ${{ env.RENOVATE_IMAGE }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dry_run }}

      - name: Run self-hosted Renovate
        if: ${{ !github.event.inputs.dry_run || github.event.inputs.dry_run == 'off' }}
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: ${{ env.RENOVATE_CONFIGURATION }}
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ${{ env.RENOVATE_IMAGE }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
