name: Renovate

on:
  #schedule:
  #  - cron: '0/30 7-8,12-13 * * 1,2,3,4,5'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run Renovate in dry-run mode'
        required: false
        type: choice
        options:
          - 'extract'
          - 'lookup'
          - 'full'
          - 'off'
        default: 'off'

permissions: {}

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get application token
        id: get_token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run self-hosted Renovate (Dry Run)
        if: ${{ github.event.inputs.dry_run && github.event.inputs.dry_run != 'off' }}
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: renovate-runner-config.json
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ghcr.io/renovatebot/renovate
          renovate-version: 37.413.3
        env:
          RENOVATE_DRY_RUN: ${{ github.event.inputs.dry_run }}

      - name: Run self-hosted Renovate
        if: ${{ !github.event.inputs.dry_run || github.event.inputs.dry_run == 'off' }}
        uses: renovatebot/github-action@21d88b0bf0183abcee15f990011cca090dfc47dd # v40.1.12
        with:
          configurationFile: renovate-runner-config.json
          token: ${{ steps.get_token.outputs.token }}
          renovate-image: ghcr.io/renovatebot/renovate
          renovate-version: 37.413.3
